"""Add Phan Thien Truy Long Thao

Revision ID: 27fd7633164f
Revises: 331b60b6a979
Create Date: 2025-11-18 20:56:25.515761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27fd7633164f'
down_revision = '331b60b6a979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_phan_thien_thao', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.drop_column('has_phan_thien_thao')

    # ### end Alembic commands ###
