"""Add detect reset logic

Revision ID: 2a6a9f6a7b8f
Revises: 5bdbe4fe25df
Create Date: 2025-11-16 21:05:22.069618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a6a9f6a7b8f'
down_revision = '5bdbe4fe25df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_detect_reset', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.drop_column('last_detect_reset')

    # ### end Alembic commands ###
