"""Add U Tam Tich Diet Thao and Trap fields

Revision ID: 331b60b6a979
Revises: 51b931e989f8
Create Date: 2025-11-18 18:55:56.906198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '331b60b6a979'
down_revision = '51b931e989f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_u_tam_thao', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('active_trap_location', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('active_trap_time', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.drop_column('active_trap_time')
        batch_op.drop_column('active_trap_location')
        batch_op.drop_column('has_u_tam_thao')

    # ### end Alembic commands ###
