"""Add Hider's Gambit flag

Revision ID: 37d57633c68b
Revises: 6ac5aab86f15
Create Date: 2025-11-18 00:17:28.115815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37d57633c68b'
down_revision = '6ac5aab86f15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_used_gambit', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.drop_column('has_used_gambit')

    # ### end Alembic commands ###
