"""Add daily take water limit

Revision ID: 51b931e989f8
Revises: d3631f7e055a
Create Date: 2025-11-18 11:52:22.629898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b931e989f8'
down_revision = 'd3631f7e055a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('take_water_turns_left', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.drop_column('take_water_turns_left')

    # ### end Alembic commands ###
