"""Add room_id, team_id, privacy to GameLog

Revision ID: 53a7ff710386
Revises: 6c57b922c07c
Create Date: 2025-11-16 09:31:58.048343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53a7ff710386'
down_revision = '6c57b922c07c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('room_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('team_id', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('privacy', sa.String(length=20), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_game_log_room_id_game_room'), 'game_room', ['room_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_log', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_game_log_room_id_game_room'), type_='foreignkey')
        batch_op.drop_column('privacy')
        batch_op.drop_column('team_id')
        batch_op.drop_column('room_id')

    # ### end Alembic commands ###
