"""Add has_tracked col

Revision ID: 5bdbe4fe25df
Revises: e7fe971ce5b7
Create Date: 2025-11-16 19:50:35.224210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bdbe4fe25df'
down_revision = 'e7fe971ce5b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_tracked', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.drop_column('has_tracked')

    # ### end Alembic commands ###
