"""Add Nhat Nguyet Tinh Luan Thao item

Revision ID: 6ac5aab86f15
Revises: d61d2ffe8498
Create Date: 2025-11-17 20:59:12.243181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ac5aab86f15'
down_revision = 'd61d2ffe8498'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_nhat_nguyet_thao', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.drop_column('has_nhat_nguyet_thao')

    # ### end Alembic commands ###
