"""Add violence_enabled to GameRoom

Revision ID: 6c57b922c07c
Revises: 9ef3da5b1cf9
Create Date: 2025-11-16 08:26:42.537658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c57b922c07c'
down_revision = '9ef3da5b1cf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('violence_enabled', sa.Boolean(), server_default=sa.text('0'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.drop_column('violence_enabled')

    # ### end Alembic commands ###
