"""Add Seawater Purifier item

Revision ID: 6df0a5d87776
Revises: 37d57633c68b
Create Date: 2025-11-18 00:58:24.782030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6df0a5d87776'
down_revision = '37d57633c68b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_seawater_purifier', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.drop_column('has_seawater_purifier')

    # ### end Alembic commands ###
