"""Add Quynh Tam Hoan Menh Thao item

Revision ID: 7d978cc5da50
Revises: c206553706db
Create Date: 2025-11-17 18:51:04.359494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d978cc5da50'
down_revision = 'c206553706db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_quynh_tam_thao', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.drop_column('has_quynh_tam_thao')

    # ### end Alembic commands ###
