"""Add daily herb random mapping

Revision ID: 7db4977fa688
Revises: cb94b1b64bd0
Create Date: 2025-11-19 10:38:15.250283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7db4977fa688'
down_revision = 'cb94b1b64bd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_herb_spawn_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('daily_herb_mapping', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.drop_column('daily_herb_mapping')
        batch_op.drop_column('daily_herb_spawn_date')

    # ### end Alembic commands ###
