"""Initial database creation

Revision ID: b314ad039291
Revises: 
Create Date: 2025-11-15 17:32:59.507710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b314ad039291'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('password', sa.String(length=150), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('avatar_image', sa.String(length=150), server_default='default.jpg', nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('game_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_message', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_game_log_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_log'))
    )
    op.create_table('game_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], name=op.f('fk_game_room_host_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_room'))
    )
    op.create_table('note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.String(length=10000), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_note_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note'))
    )
    op.create_table('player_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('game_status', sa.String(length=50), nullable=True),
    sa.Column('team', sa.String(length=10), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('current_location', sa.String(length=10), nullable=True),
    sa.Column('current_water', sa.Float(), nullable=True),
    sa.Column('last_action_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('search_turns_left', sa.Integer(), nullable=True),
    sa.Column('gather_turns_left', sa.Integer(), nullable=True),
    sa.Column('has_remote_water', sa.Boolean(), nullable=True),
    sa.Column('has_teleport', sa.Boolean(), nullable=True),
    sa.Column('detect_turns_left', sa.Integer(), nullable=True),
    sa.Column('is_detecting', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['game_room.id'], name=op.f('fk_player_state_room_id_game_room')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_player_state_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_player_state')),
    sa.UniqueConstraint('user_id', name=op.f('uq_player_state_user_id'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_state')
    op.drop_table('note')
    op.drop_table('game_room')
    op.drop_table('game_log')
    op.drop_table('user')
    # ### end Alembic commands ###
