"""Add Spirit Class and Stun

Revision ID: bd359a261536
Revises: 27fd7633164f
Create Date: 2025-11-18 23:18:47.591780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd359a261536'
down_revision = '27fd7633164f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spirit_class', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('stun_expires_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.drop_column('stun_expires_at')
        batch_op.drop_column('spirit_class')

    # ### end Alembic commands ###
