"""Add GameChat table

Revision ID: c206553706db
Revises: 2a6a9f6a7b8f
Create Date: 2025-11-17 18:11:57.874536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c206553706db'
down_revision = '2a6a9f6a7b8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_body', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=20), nullable=True),
    sa.Column('team_id', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['game_room.id'], name=op.f('fk_game_chat_room_id_game_room')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_game_chat_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_game_chat'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_chat')
    # ### end Alembic commands ###
