"""Refactor seawater gather to boolean reset

Revision ID: cb94b1b64bd0
Revises: bd359a261536
Create Date: 2025-11-19 10:15:46.929208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb94b1b64bd0'
down_revision = 'bd359a261536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gathered_seawater_today', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.drop_column('gathered_seawater_today')

    # ### end Alembic commands ###
