"""Add Tram Tuong herb timer

Revision ID: d3631f7e055a
Revises: 6df0a5d87776
Create Date: 2025-11-18 10:19:14.177893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3631f7e055a'
down_revision = '6df0a5d87776'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tram_tuong_herb_day', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tram_tuong_herb_minute', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.drop_column('tram_tuong_herb_minute')
        batch_op.drop_column('tram_tuong_herb_day')

    # ### end Alembic commands ###
