"""Add Ly Sau Tan Phach Thao item

Revision ID: d61d2ffe8498
Revises: 7d978cc5da50
Create Date: 2025-11-17 19:37:56.437853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61d2ffe8498'
down_revision = '7d978cc5da50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_ly_sau_thao', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.drop_column('has_ly_sau_thao')

    # ### end Alembic commands ###
