"""Add active post time column for Tracker

Revision ID: e7fe971ce5b7
Revises: f2d2659fbe20
Create Date: 2025-11-16 13:47:53.387830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7fe971ce5b7'
down_revision = 'f2d2659fbe20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_active_post_time', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('player_state', schema=None) as batch_op:
        batch_op.drop_column('last_active_post_time')

    # ### end Alembic commands ###
