"""Add room mode

Revision ID: e84caf9c48f5
Revises: 7db4977fa688
Create Date: 2025-11-19 16:14:41.203846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84caf9c48f5'
down_revision = '7db4977fa688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.drop_column('mode')

    # ### end Alembic commands ###
