"""Add beast squares to GameRoom

Revision ID: f2d2659fbe20
Revises: 53a7ff710386
Create Date: 2025-11-16 10:21:15.381990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2d2659fbe20'
down_revision = '53a7ff710386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.add_column(sa.Column('beast_square_1', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('beast_square_2', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_room', schema=None) as batch_op:
        batch_op.drop_column('beast_square_2')
        batch_op.drop_column('beast_square_1')

    # ### end Alembic commands ###
